### ISSUE TITLE
[Question] How to obtain the text version of a character's voice record?

### ISSUE THREAD

**Issue by unknowed-ER** [isHarryh/Ark-Unpacker#11]
Thank you for your work! I have obtained the audio recordings of all the staff members, but I am unable to obtain the corresponding text versions. Where should I find the answer?

**Comment by isHarryh** [comment]
https://github.com/Kengxxiao/ArknightsGameData_YoStar

This repo may have some relevant data of the character's voice text (International server ver.)

However, there are still some difficulties to match the text with the audio automatically.

**Comment by unknowed-ER** [comment]
Sincere thanks for your reply. I crawled the required data from HTTP:prts.wiki .

**Comment by isHarryh** [comment]
Now ArkUnpacker v3.2.0+ has implemented audio data extraction.
