### ISSUE TITLE
[Question] 询问干员台词对应的文本存储位置及其对应映射表

### ISSUE THREAD

**Issue by PoTaTo-Mika** [isHarryh/Ark-Unpacker#16]
如题。

**Comment by isHarryh** [comment]
#### 干员台词 AB 文件存储位置
`gamedata/excel/charword_tablexxxxxx.ab`（其中xxxxxx是6位十六进制数）

### 提取方法
使用 v3.x 解包器，先使用自定义资源解包功能将上述 AB 文件解包。然后使用 FlatBuffers 数据解码功能，对解包后的文件进行解码，得到 JSON 文件。

### 解码后的格式
解码后的 JSON 文件 `charword_tablexxxxxx.json` 如下所示：
![charword_table](https://github.com/user-attachments/assets/c8279635-770f-4c0b-8b68-0519ebd84998)

干员台词主要位于字段 `CharWords` 中，如下所示：
![CharWords](https://github.com/user-attachments/assets/0bb0d7ca-b400-436c-a9e9-b0d93fdee7e2)

键名中的 `_CN_` 应该并不是指这个语音是“中文的配音“，而是指这个语音的”显示的文本是中文的“（因为我们解包的是中国服）。要想得知这个语音有哪些语言，你需要在字段 `VoiceLangDict` 中查找，如下所示。
![VoiceLangDict](https://github.com/user-attachments/assets/d0fca396-79bc-4b0f-80ec-1119b7dd0fd4)

### 映射到音频文件
根据 `VoiceLangDict` 的提示，去 `audio/sound_beta_2` 文件夹中找到对应的语言包，如下所示：
![sound_beta_2](https://github.com/user-attachments/assets/24279ba3-1084-43c9-a8b8-7b34b709c57d)

然后解包该语言包，利用 `CharWords` 的 `VoiceAsset` 字段，就能映射语音文件到台词文本了。
