### ISSUE TITLE
[Enhancement] 关于准确区分战斗小人图片正背面的方法

### ISSUE THREAD

**Issue by Baka632** [isHarryh/Ark-Unpacker#4]
在包含atlasFile信息的那个MonoBehavior里面有一个指向Material文件的PathID
![image](https://user-images.githubusercontent.com/48171809/206454277-04b12fe0-5548-437c-bb6e-859867350d09.png)

而那个Material文件里面，就包含了指向RGB通道图Texture2D对象与Alpha通道图Texture2D对象的PathID!
![image](https://user-images.githubusercontent.com/48171809/206454995-656fce8e-96af-4e43-a00c-0c82f962412c.png)

[_参考项目:ArknightsResources.Utility_](https://github.com/ArknightsResources/Utility/blob/master/src/AssetBundleHelper.cs#L76)

**Comment by isHarryh** [comment]
感谢您的支持，我们后续会验证并尝试改进！

**Comment by isHarryh** [comment]
已成功根据你的思路实现区分战斗小人的正背面图片：https://github.com/isHarryh/Ark-Unpacker/commit/9385e00fb03615f336df58ebf8e455173a504d2f

**Comment by isHarryh** [comment]
在 ArkUnpacker v4.0 及先前的版本（[代码](https://github.com/isHarryh/Ark-Unpacker/blob/ae9c79386081c7e12b7f7fcfd0f0bffa7f17333a/src/ResolveAB.py#L181)）中，采用的解析策略是：

1. 找到所有包含 `skeletonDataAsset` 字段的 MonoBehavior 对象（命名为 `mono`）。
2. 根据 `mono` 的 `skeletonDataAsset` 字段值，在当前 AB 文件中按 pathID 查找对应的 MonoBehavior 对象（命名为 `mono_sd`）。
3. 根据 `mono_sd` 的 `skeletonJSON` 字段，找到对应的 Skel 文本对象；根据 `atlasAssets` 字段，查找对应的 MonoBehavior 对象（命名为 `mono_ad`）。
4. 根据 `mono_ad` 的 `atlasFile` 字段，找到对应的 Atlas 文本对象；根据 `materials` 字段，使用 @Baka632 提供的办法找到纹理图。

自《明日方舟》v2.5.60 开始，上述方法不再完全有效。因为某些 Spine 模型的 `mono` 对象与 `mono_sd` 等其余对象分别位于不同的文件中。为了应对这一变更，计划对解析策略作出如下修改：

- 不再查找包含 `skeletonDataAsset` 字段的 `mono` 对象了，改为直接查找包含 `skeletonJSON` 字段的 `mono_sd` 对象。也就是跳过了第一个步骤。

**Comment by isHarryh** [comment]
在 #26 中发现，部分干员的战斗小人的正面和背面的 png 和 atlas 是共用的，这会导致无法完整地导出正面和背面的模型。

先前采用的区分策略是：根据 atlas 中的组件名称进行判断，如果以 `F_` 或 `C_` 开头的组件数量 大于 以 `B_` 开头的组件数量，则认为是正面（Front），否则认为是背面（Back）。

计划于 ArkUnpacker v4.1.1 作出修改：优先寻找 `CharacterAnimator` 这一 MonoBehavior 对象，在该对象中查找 `_front` 和 `_back` 的指向，从而确定骨骼是正面还是背面。如果此方法失效，则回退到”根据 atlas 中的组件名称进行判断“的方式。
