### ISSUE TITLE
[Question] exe无法运行

### ISSUE THREAD

**Issue by Hakuin123** [isHarryh/Ark-Unpacker#5]
rt，系统版本Windows 11 (64位)

是否需要额外安装环境？

**Comment by Hakuin123** [comment]
（抱歉一开始字打错了实在不好意思qwq）

**Comment by Hakuin123** [comment]
录屏：

https://user-images.githubusercontent.com/108911712/216810193-85107818-6aa4-4625-abd7-e75c2a4559d3.mp4

**Comment by isHarryh** [comment]
录屏无法查看，是全黑的。请你使用命令行运行exe查看回显。

**Comment by isHarryh** [comment]
请提供有效的信息，以便进一步确定问题，否则议题将关闭。

**Comment by Hakuin123** [comment]
不清楚具体如何操作

问题描述：启动程序后弹出窗口瞬间关闭

**Comment by isHarryh** [comment]
> 录屏无法查看，是全黑的。请你使用命令行运行exe查看回显。

~~命令行不会吗~~  请用Win+R组合键运行`cmd`，然后弹出一个黑色窗口（命令行），将exe文件拖入进去，按下回车。

**Comment by isHarryh** [comment]
> 录屏无法查看，是全黑的。请你使用命令行运行exe查看回显。

之后应该会有异常信息回显，将该回显截图或复制给我。

**Comment by Hakuin123** [comment]
不晓得能以这种方法运行…知识增加.gif
![屏幕截图 2023-02-07 213350](https://user-images.githubusercontent.com/108911712/217260191-a9191481-78ac-4789-ab88-3a6585489d28.png)

**Comment by isHarryh** [comment]
可能是权限问题，请讲exe移动到其他目录，然后以管理员权限运行。

**Comment by Hakuin123** [comment]
已尝试，回显无差别qwq

**Comment by isHarryh** [comment]
> 已尝试，回显无差别qwq

暂时无法确定问题。如有需要请使用源代码运行（在你熟悉Python的情况下），使用方法参见`docs/ForDevelopers.md`文档。
