### ISSUE TITLE
[Enhancement] Repack AB files from extracted files

### ISSUE THREAD

**Issue by Nyantasan59** [isHarryh/Ark-Unpacker#6]
Hello,

Thank you for your tool that allows me to get the AB files already extracted!

Do you think in the future also do the opposite? I mean be able to recreate the AB file from the extracted file?

Thanks in advance,
Best regards,
Nyantasan59

**Comment by isHarryh** [comment]
Glad that this tool is useful to you. It is considered that repacking is a difficult function and it is unpacking that is the main function of this tool. So, I regret to tell you that we will not realize repacking.
Maybe you can use the game development software - Unity, to edit AB files.

**Comment by Nyantasan59** [comment]
I understand perfectly, I also tried on my side (without success) however there are too many notions that are unknown to me between the AES keys, padding, manipulation of JSONs, the UnityPy library, etc. That's why I tried my luck ^^

Anyway, thanks again for your tool!
