### ISSUE TITLE
[Enhancement] 自定义一键执行模式的线程数

### ISSUE THREAD

**Issue by WallBreakerNO4** [isHarryh/Ark-Unpacker#8]
如题，我电脑的CPU是5700X，默认的8线程无法跑满CPU，请求一个简单的方式更改执行的线程数而不是写死8线程

**Comment by isHarryh** [comment]
感谢反馈，后续会添加配置文件使用户可以更改部分程序常量。

**Comment by isHarryh** [comment]
已于 d01454d9ada18966a62a90fae9666574f028f6e2 添加了配置文件功能。将于`v2.3`中发行。

**Comment by isHarryh** [comment]
`v2.3.0`已发布，配置方法参见[此处](https://github.com/isHarryh/Ark-Unpacker/blob/v2.3/docs/ConfigFile.md)。
