### ISSUE TITLE
[Question] 现版本无法处理敌人数据

### ISSUE THREAD

**Issue by loveaca-sunlight** [isHarryh/Ark-Unpacker#9]
于 2023年8月8日 使用明日方舟最新版本解包，无法在 `battle` 文件夹下找到正确的敌人Spine素材。
请问可以提供可执行解包的旧版APK，或者更新资源位置文档么？
如果可以的话感激不尽！

**Comment by isHarryh** [comment]
已证实敌人Spine素材位于 `battle/prefabs/enemies`，以 `ememy_xx.ab` 进行分组存放，并未出现丢失的情况。
